# -*- coding: utf-8 -*-
"""examen ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQx_oFog_68k5lr__3x2b3nzyUSO5VBi

**Agente de Rescate en el Laberinto**
Búsqueda BFS vs A* con Heurística Manhattan

**Materia**: Inteligencia Artificial

**Alumno**: Pérez Moncayo Gonzalo Sebastian

**Problema**: Un robot autónomo debe localizar a una víctima en un laberinto de 5x5 celdas.  
El agente parte desde la esquina superior izquierda S y debe llegar a la víctima V, evitando obstáculos X.

**1. Importaciones y Definición del laberinto texto en negrita**
"""

from collections import deque
import heapq

GRID = [
    ['S', '.', 'X', '.', '.'],
    ['.', '.', '.', 'X', '.'],
    ['X', '.', '.', '.', '.'],
    ['.', 'X', '.', 'X', '.'],
    ['.', '.', '.', '.', 'V'],
]

ROWS = len(GRID)
COLS = len(GRID[0])

START = next((r, c) for r in range(ROWS) for c in range(COLS) if GRID[r][c] == 'S')
GOAL  = next((r, c) for r in range(ROWS) for c in range(COLS) if GRID[r][c] == 'V')

DIRECTIONS = [(-1, 0, '↑'), (1, 0, '↓'), (0, -1, '←'), (0, 1, '→')]

def is_valid(r, c):
    """Verifica si una celda es transitable."""
    return 0 <= r < ROWS and 0 <= c < COLS and GRID[r][c] != 'X'

print(f" Laberinto cargado | Inicio: {START} | Objetivo: {GOAL}")
print()
print("Mapa inicial:")
for row in GRID:
    print('  ' + '  '.join(row))

"""## 2. BFS — Búsqueda en Anchura

BFS explora el laberinto nivel por nivel, garantizando el camino con menor número de pasos.  
Usa una cola FIFO y no necesita ninguna heurística. texto en negrita
"""

def reconstruct(parent, goal):
    """Reconstruye el camino desde el nodo goal hasta el inicio."""
    path = []
    node = goal
    while node in parent:
        node, mov = parent[node]
        path.append((node, mov))
    path.reverse()
    return path

def full_path_coords(path):
    """Convierte la secuencia de movimientos en coordenadas (fila, col)."""
    node = START
    result = [node]
    delta = {'↑': (-1,0), '↓': (1,0), '←': (0,-1), '→': (0,1)}
    for _, mov in path:
        dr, dc = delta[mov]
        node = (node[0]+dr, node[1]+dc)
        result.append(node)
    return result

def bfs():
    """Búsqueda en Anchura (BFS)."""
    queue    = deque([START])
    visited  = {START}
    parent   = {}
    expanded = 0

    while queue:
        node = queue.popleft()
        expanded += 1

        if node == GOAL:
            return reconstruct(parent, node), expanded

        r, c = node
        for dr, dc, mov in DIRECTIONS:
            nb = (r+dr, c+dc)
            if is_valid(*nb) and nb not in visited:
                visited.add(nb)
                parent[nb] = (node, mov)
                queue.append(nb)

    return None, expanded

bfs_path, bfs_expanded = bfs()
bfs_coords = full_path_coords(bfs_path)
bfs_moves  = ' '.join(m for _, m in bfs_path)

print("═" * 45)
print("  BFS — Búsqueda en Anchura")
print("═" * 45)
print(f"  Nodos expandidos : {bfs_expanded}")
print(f"  Longitud camino  : {len(bfs_coords)-1} pasos")
print(f"  Movimientos      : {bfs_moves}")
print(f"  Coordenadas      : {bfs_coords}")

"""## 3. A* — Búsqueda Informada (Heurística Manhattan)

A* combina el **costo real** `g(n)` con una **estimación heurística**.

La heurística **Manhattan** se define.

Es **admisible** (nunca sobreestima) en cuadrículas sin movimiento diagonal, lo que garantiza optimalidad.
"""

def manhattan(a, b):
    """Heurística Manhattan entre dos celdas."""
    return abs(a[0]-b[0]) + abs(a[1]-b[1])

def astar():
    """Búsqueda A* con heurística Manhattan."""
    heap     = []
    visited  = {}
    parent   = {}
    expanded = 0

    heapq.heappush(heap, (manhattan(START, GOAL), 0, START))

    while heap:
        f, g, node = heapq.heappop(heap)

        if node in visited and visited[node] <= g:
            continue
        visited[node] = g
        expanded += 1

        if node == GOAL:
            return reconstruct(parent, node), expanded

        r, c = node
        for dr, dc, mov in DIRECTIONS:
            nb = (r+dr, c+dc)
            if not is_valid(*nb):
                continue
            ng = g + 1
            if nb not in visited or visited[nb] > ng:
                parent[nb] = (node, mov)
                heapq.heappush(heap, (ng + manhattan(nb, GOAL), ng, nb))

    return None, expanded

astar_path, astar_expanded = astar()
astar_coords = full_path_coords(astar_path)
astar_moves  = ' '.join(m for _, m in astar_path)

print("═" * 45)
print("  A* — Búsqueda con Heurística Manhattan")
print("═" * 45)
print(f"  Nodos expandidos : {astar_expanded}")
print(f"  Longitud camino  : {len(astar_coords)-1} pasos")
print(f"  Movimientos      : {astar_moves}")
print(f"  Coordenadas      : {astar_coords}")

"""### 4. Visualización del Camino Encontrado"""

def print_grid(coords, title):
    path_set = set(coords)
    print(f"\n{'═'*30}")
    print(f"  {title}")
    print(f"{'═'*30}")
    for r in range(ROWS):
        row_str = "  "
        for c in range(COLS):
            cell = GRID[r][c]
            if cell == 'S':
                row_str += ' S '
            elif cell == 'V':
                row_str += ' V '
            elif cell == 'X':
                row_str += ' X '
            elif (r, c) in path_set:
                row_str += ' * '
            else:
                row_str += ' . '
        print(row_str)
    print()

print_grid(bfs_coords,   "BFS  — Camino encontrado")
print_grid(astar_coords, "A*   — Camino encontrado")

"""## 5. Comparación de Desempeño"""

print("═" * 50)
print("  COMPARACIÓN DE DESEMPEÑO")
print("═" * 50)
print(f"  {'Métrica':<28} {'BFS':>8} {'A*':>8}")
print(f"  {'─'*44}")
print(f"  {'Nodos expandidos':<28} {bfs_expanded:>8} {astar_expanded:>8}")
print(f"  {'Longitud del camino (pasos)':<28} {len(bfs_coords)-1:>8} {len(astar_coords)-1:>8}")
print(f"  {'Usa heurística':<28} {'No':>8} {'Sí':>8}")
print(f"  {'Garantiza óptimo':<28} {'Sí':>8} {'Sí':>8}")
print(f"  {'Caminos iguales':<28} {'Sí' if bfs_coords == astar_coords else 'No':>8}")
reduccion = round((1 - astar_expanded/bfs_expanded)*100, 1)
print(f"\n  A* expandió un {reduccion}% menos nodos que BFS")

"""# **Conclusiones**

### Análisis

- **Ambos algoritmos** encuentran el camino óptimo de **8 pasos**
- A* es más eficiente: expande 3 nodos menos (18% de reducción) gracias a la heurística Manhattan, que descarta exploraciones en direcciones alejadas del objetivo.
- **BFS** garantiza el óptimo en grafos con costo uniforme; **A*** lo garantiza cuando `h(n)` es admisible, como lo es Manhattan en cuadrículas sin diagonales.

### Proyección a un entorno 10×10

En un laberinto de **100 celdas**, la ventaja de A* sería mucho mayor:
- **BFS** exploraría en "ondas concéntricas", potencialmente visitando la mayoría de celdas libres.
- **A*** focalizaría la búsqueda hacia el objetivo, expandiendo significativamente menos nodos y reduciendo tanto tiempo de cómputo como uso de memoria.

> **Conclusión:** A* sería el algoritmo **claramente preferible** en entornos más grandes, mientras que BFS es suficiente para espacios pequeños como este laberinto 5×5.
"""